stages: [build, deploy]

variables:
  KUBE_NAMESPACE: "${KUBE_NAMESPACE}"

build:
  stage: build
  image: docker:24
  services: [docker:dind]
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  only: [main]

deploy:
  stage: deploy
  image: bitnami/kubectl:1.30
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
  script: |
    helm repo add gitlab https://charts.gitlab.io
    helm upgrade --install recommender gitlab/auto-deploy-app \
      --namespace "$KUBE_NAMESPACE" --create-namespace \
      --set image.repository="$CI_REGISTRY_IMAGE" \
      --set image.tag="$CI_COMMIT_SHORT_SHA" \
      --set gitlab.app=myapp \
      --set env[0].name=NEXTAUTH_URL \
      --set env[0].value=https://$CI_PROJECT_NAME.$KUBE_BASE_DOMAIN
  environment:
    name: production
    url: https://$CI_PROJECT_NAME.$KUBE_BASE_DOMAIN
  only: [main]
