image: docker:26
services:
  - docker:dind

# GitLab’s Docker-in-Docker needs this
variables:
  DOCKER_TLS_CERTDIR: ""       # disable TLS inside DinD for simplicity

stages: [test, build]

# ─────────────────── tests only ───────────────────
unit-tests:
  stage: test
  script:
    - echo "🔎 run your npm / pytest / go test commands here"
  tags: [docker]

# ─────────────────── optional container build ─────
docker-build:
  stage: build
  rules:
    # skip the whole job unless you deliberately enabled it
    - if: '$BUILD_DOCKER_IMAGE == "true"'
  script:
    # log in to GitLab registry (credentials are injected automatically)
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    # build & push
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  tags: [docker]
ba
# .gitlab-ci.yml
stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""  # нужно для docker:dind без TLS

docker-build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  before_script:
    # Безопасный логин
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build -t "$CI_REGISTRY_USER/myimage:latest" .
    - docker push "$CI_REGISTRY_USER/myimage:latest"
