version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: dev-secret-123
      NEXTAUTH_URL: http://localhost:3000
    command: npm run dev

volumes:
  node_modules:
